### PR TITLE
Fix (?) crash with PM window

### PR DESCRIPTION
**Pull request by turbedi**

### CODE REVIEW

**Comment by turbedi** [comment]
@Withoutatrace Can you try if this fixes the crash you mentioned?

**Comment by Withoutatrace** [comment]
I will attempt to see if my local client will work at all, but yeah.

**Comment by turbedi** [comment]
@Withoutatrace Any update?

**Comment by turbedi** [comment]
Any update?

**Comment by MidwayMarshall** [comment]
https://github.com/po-devs/android-client/commit/130aec3ae84514dc44a2be25067beecd69589944

**Pull request closed without merging**
