### PR TITLE
Unreleased Pokemon uIDFill

### PR DESCRIPTION
**Pull request by VeteranPadgett**
"pokemons" array was filled with keys using "released.txt" and so Pokemon like Mimikyu-Broken wouldn't exist and crash the client later when it tried to look for them.

### CODE REVIEW

**Comment by turbedi** [comment]
<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3<3
Gonna test the fix in the evening and then merge it if everything is fine.

**Comment by MidwayMarshall** [comment]
Why does Mimikyu-Broken need to be in the database if it isn't released?

**Comment by VeteranPadgett** [comment]
Because that form can exist in battle and has a separate sprite.

**Comment by MidwayMarshall** [comment]
Okay. So it IS released it just isn't a selectable form like megas.  Which is how I made it as a database entry

**Pull request closed without merging**
