### PR TITLE
Item list changes

### PR DESCRIPTION
**Pull request by VeteranPadgett**
Made it so x_useful.txt doesn't need useless boolean at the end of each line. Also fixed which berries are displayed.

### CODE REVIEW

**Comment by MidwayMarshall** [comment]
Fixed the berries displayed?

**Comment by turbedi** [comment]
The teambuilder currently displays all berries, not just the berries that are available in the selected Gen.

**Comment by MidwayMarshall** [comment]
usefulThisGeneration is what the teambuilder uses no? Is released_berries.txt incorrect?


final ArrayList<Integer> released_berries = new ArrayList<Integer>();
            InfoFiller.plainFill("db/items/" + Generation + "G/released_berries.txt", new Filler() {
usefulThisGeneration = new int[released_items.size() + released_berries.size()];

**Comment by turbedi** [comment]
released_berries.txt is correct in combination with berry_useful.txt (just like the teambuilder does with released_items.txt and item_useful.txt). There are items that are released in a specific Gen, but aren't actually useful in a battle and these items get filtered out by item_useful.txt/berry_useful.txt

**Comment by VeteranPadgett** [comment]
released_berries is correct. The teambuilder takes the intersection of released_berries and berry_useful

for (int i = released_berries.size() - 1; i > -1; i--) {
                if (!primitiveContains(released_berries.get(i))) {
                    released_berries.remove(released_berries.get(i));

primitiveContains is filled with the useful ones (before was just all berries) since there is no need to display Razz Berry, etc that do nothing.

**Pull request merged**
