### PR TITLE
Fix possible crashes in settings

### PR DESCRIPTION
**Pull request by turbedi**
This should work, right?

### CODE REVIEW

**Comment by MidwayMarshall** [comment]
in res/xml/settings.xml

android:inputType="number" 
should prevent non numerical input

**Comment by turbedi** [comment]
But it still crashes when the entered value is higher than an integer :P

**Comment by MidwayMarshall** [comment]
Maybe use long.parseLong, give someone's thumbs a workout

**Comment by MidwayMarshall** [comment]
Need to declare i before the try block?

**Comment by coyotte508** [comment]
rather, make try{} encompass everything except the error case and do nothing inside the catch.

**Comment by MidwayMarshall** [comment]
I force updated the commit

**Pull request merged**
