### PR TITLE
Fix item_useful.txt

### PR DESCRIPTION
**Pull request by VeteranPadgett**
The teambuilder was only showing berries because the 1's at the end of each line was removed. fill(int i, String s) expects a space then a string on each line or else it discards the rest of the input. I added the 1's back, but you could also implement fill to take a single int if you want to get rid of them.

### CODE REVIEW

**Comment by Fuzzysqurl** [comment]
I believe I changed that because it was quicker to do that than type 40 1s for gen 7 items. :)

**Comment by VeteranPadgett** [comment]
Yeah, I don't know why we would need the 1's in the first place lol. Same thing as the Mimikyu problem though, the android db has to either keep the original style or have code added to handle the new input style. Did you have to change anything besides the txt file when you removed the 1 for windows client?

**Comment by turbedi** [comment]
@VeteranPadgett  https://github.com/po-devs/pokemon-online/commit/f9bdad5a8d4f50cd7da29bd1a3b05f4880b73697#diff-22205dec8863e5b5c1a09a72907c41cc
I'd prefer to add/change the code of the Android Client instead of editing the db files :x

**Comment by VeteranPadgett** [comment]
Ok. Close this then and I'll do a different pr.

**Pull request closed without merging**
